---
- name: Docker Installation Template
  hosts: dockerservers
  remote_user: root
  tasks:
   - name: Prerequisites packet=yum-utils
     become: true
     become_user: root
     yum: 
      name: yum-utils 
      state: latest
   - name: Prerequisites packet=device-mapper-persistent-data
     become: true
     become_user: root
     yum:
      name: device-mapper-persistent-data
      state: latest
   - name: Prerequisites packet=lvm2
     become: true
     become_user: root
     yum:
      name: lvm2
      state: latest
#Create Docker user
   - name: Create user 'dockeruser'
     become: true
     become_user: root
     user:
      name: dockeruser
#Add docker repository for installation
   - name: Add Docker repo
     get_url:
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/docker-ce.repo
     become: yes
   - name: Install Docker
     package:
       name: docker-ce
       state: latest
     become: yes
#Add user "dockeruser" to "docker" group
   - name: Adding user dockeruser
     user: name=dockeruser
           group=docker
           append=yes
#Start and enalbe docker service
   - name: Enable and start docker.service
     systemd:
       name: docker.service
       state: started
       enabled: yes
#Change ExecStart to expose DOCKER REST API
   - name: Change ExecStart to expose DOCKER REST API
     become: yes
     become_user: root
     lineinfile:
       path: /etc/systemd/system/multi-user.target.wants/docker.service
       regexp: "ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock" 
       line: "ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://0.0.0.0:2375"
       state: present
       backup: yes
#Daemon-realod and docker restart
   - name: Restart service docker oafter daemon-reload
     systemd:
       state: restarted
       daemon_reload: yes
       name: docker.service
      